env:
  browser: true
  es2021: true
  node: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 'latest'
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'unused-imports'
rules:
  semi: [2, 'never']
  '@typescript-eslint/no-unused-vars': 'off'
  'unused-imports/no-unused-vars': [2, { args: 'after-used', argsIgnorePattern: '^_' }]
  'unused-imports/no-unused-imports': 'error'
  quotes: [2, 'single', 'avoid-escape']
